---
- name: enable, and start redis.
  systemd:
    name: "redis-server.service"
    enabled: true
    masked: false
    state: started


- name: Wait for redis to startup
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ item }}"
    delay: 5
    connect_timeout: 1
  when: redis_activate|bool
  with_items:
    - "{{ redis_port }}"

- name: enable, and start redis-sentinel.
  systemd:
    name: "redis-sentinel.service"
    enabled: true
    masked: false
    state: started

- name: Wait for redis-sentinel to startup
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 5
    connect_timeout: 1
  when: redis_sentinel_activate|bool
  with_items:
    - "{{ redis_sentinel_port }}"
